Working, before parallelization

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -32,11 +32,50 @@ tasks:
     cmds:
       - pipenv install --deploy --ignore-pipfile --dev
 
+  runner-apt-install:
+    desc: Install something on a GitHub Actions runner via apt
+    internal: true
+    status:
+      - '{{if eq .GITHUB_ACTIONS "true"}}exit 1{{end}}'
+    requires:
+      vars: [TOOLS]
+    preconditions:
+      - sudo apt-get update
+    platforms: [linux]
+    cmds:
+      - for:
+          var: TOOLS
+          split: ','
+          as: tool
+        cmd: apt-get install -y --no-install-recommends {{.tool}}
+
+  mac-brew-install:
+    desc: Install something on a mac via brew
+    internal: true
+    platforms: [darwin]
+    requires:
+      vars: [TOOLS]
+    cmds:
+      - for:
+          var: TOOLS
+          split: ','
+          as: tool
+        cmd: brew install {{.tool}}
+
+  init-install-tools:
+    desc: Install required tools
+    internal: true
+    cmds:
+      - task: runner-apt-install
+        vars:
+          TOOLS: xclip
+
   init:
     desc: Initialize the repo for local use; intended to be run after git clone
     deps: [lock]
     cmds:
       - task: init-pipenv
+      - task: init-install-tools
       - pipenv run playwright install --with-deps chromium
 
   build:
@@ -59,10 +98,23 @@ tasks:
     desc: Run the project tests
     deps: [clean, build]
     env:
-      LOG_LEVEL: INFO
+      LOG_LEVEL: '{{ .CLI_ARGS | default "INFO" }}'
     cmds:
-      # TODO: Remove || true when we have functional tests
-      - pipenv run pytest tests --log-cli-level "${LOG_LEVEL}" || true
+      - pipenv run pytest tests --log-cli-level "${LOG_LEVEL}"
+
+  destroy:
+    desc: Run terraform destroys and cleanup all of the test terraform modules
+    cmds:
+      - |
+        for dir in $(find tests -type d -maxdepth 1 -mindepth 1); do
+          cd "${dir}"
+          failure=$?
+          if [[ ${failure} -ne 0 ]]; then
+            echo "Failed to cd into ${dir}"
+            exit 1
+          fi
+          terraform destroy -auto-approve
+        done
 
   update:
     desc: Update the project dev and runtime dependencies, and other misc components
